language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key:
      secure: ''
    on:
      tags: true
      node: '4'
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "LllCE2tMAPmhRI0JUbhgkI+UlfAPsnIqG38ysZFScgKQGZ5g+sUt1uVSydfLoX/RQNRbUkiWwieOagcwORPUJJdh2KjXEm/HWcqES/Q3V/8/JeWKa+G/E+2IPLGYba1EWWHyH3NIeNIcTvm50FxAQDJYRYPEq1cg1j0mb10kZu6QKTAqel8rgfVdxJSUsXENCG6CKu+Gbx07/IDws+mc/I4wl/hf3pDKoGp0bDw76yWpIYEy7LjrNfvjmkMHNspbqpRlEDL0NJkHKhh8XlEMTwxdCYopxHDce9adXnrnR5m2bkwLMU+sfcfskG2XyfUK6tk1i4t2uzk54ZDxnwm75yDgY3ceqo5orfnEgDhb6vegj1IPLhzhhDjQzWZd2v8duYSJqhzG+AVu4hYcC/V1lwBHceyE/mWs/G7aVZfCTQqZCOYm+O+JJ+j5AyWjSWrUV3fH98zAivhboe1GQUWq8UlPIW3Ke/icy0zDP8GuhuA1JJCPnaHjPuNjmazOvFvwJnNK5Pb/RB6Og1KpovoWTezfRDRxmt66EmHEA5NU8NXoIIO+foeZ+6tb5mn2BB3sZYbVxriRpJiA7Tecz7kV3j3sSDw2LWdX2krst0qD9EebAkivmHxRpuUfKgYggbKR+FTGEZ++302RfKcODShM1hhWj/rub6hYZc68h3DEAeA="
addons:
  code_climate:
    repo_token:
      secure: 'jMib2LNFGzfKiINRK0fOwibNgHnizTh87Fb1YK0Q2UpWtF7WiigEBhNyiX3pF02HH3iRuICHKYzE1QrZbIzk88XVTUhilO7vI+h1VpgbcuOxq7nkE+kSfxAiTpkD6eY7c0s8wSViKTPOVPPrpRfp8RYYLx6Vcox9jlN7StOHAgDuiwGwHPZ6lz2KGzX1xx8Z8ZLnHIIihv7rqQgetu7BNoPcrPv2Dz63qZI3DbFPWVJIe05B6I7iuiPgzlRZzIvUWofpp6zM5jT9ktrGyF786sh15mDzixoDzUDKmw6ptbc7MeoEuT2Co7FYr4LibXClSaoXcfKJ37/6E5Xzya1e7Sz/83+H1Xi34LCUcVHySzmCWSMWa1fGnZMCHJUdhCVmY5EJMQSGJEvPwHt+1beRYsWAm0cP2RsZ3LhIj9uB6jVXUz1pmhlkL2AFiuBZ2D3vKw4DTtnKqBounsI/FFm0Z0bhsOfkUs7HzAtdnPGjkzlHYW//YvncmTaO0fnMswJVLTKlMq9J/VnqLF1bH2CVYO9zBXIvf786SwgNrWAW/nmyOHE0kOzo79OVfm147qTPmF93ajwLWA814HUK8xpPZ5nMLgFaPpqlNO8co/5gpGm3cRrxRQ2yeOMCealz/EVJYS9LUmYugR42Ayg6iHLRoqwCKdtsjhMFZNEAOwsMs80='
